# Endereço do Kafka
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_CONSUMER_GROUP_ID:transactions}
      auto-offset-reset: ${KAFKA_AUTO-OFFSET-RESET:latest}

server:
  port: 8081